### ISSUE TITLE
How to install Enet.

### ISSUE THREAD

**Issue by Hakorr** [coldchip/growtopiaserver#10]
How to download it to Kali Linux.

**Comment by Hakorr** [comment]
g++ server.cpp Player/player.cpp Command/command.cpp Login/login.cpp Packet/packet.cpp Utils/utils.cpp World/world.cpp -o server -lenet -lpthread
server.cpp:7:10: fatal error: enet/enet.h: No such file or directory
 #include <enet/enet.h>
          ^~~~~~~~~~~~~
compilation terminated.
Player/player.cpp:3:10: fatal error: enet/enet.h: No such file or directory
 #include <enet/enet.h>
          ^~~~~~~~~~~~~
compilation terminated.
In file included from Command/command.cpp:3:
Command/command.h:3:10: fatal error: enet/enet.h: No such file or directory
 #include <enet/enet.h>
          ^~~~~~~~~~~~~
compilation terminated.
In file included from Login/login.cpp:6:
Login/../Player/player.h:2:10: fatal error: enet/enet.h: No such file or directory
 #include <enet/enet.h>
          ^~~~~~~~~~~~~
compilation terminated.
Packet/packet.cpp:2:10: fatal error: enet/enet.h: No such file or directory
 #include <enet/enet.h>
          ^~~~~~~~~~~~~
compilation terminated.
Utils/utils.cpp:2:10: fatal error: enet/enet.h: No such file or directory
 #include <enet/enet.h>
          ^~~~~~~~~~~~~
compilation terminated.
World/world.cpp:2:10: fatal error: enet/enet.h: No such file or directory
 #include <enet/enet.h>

**Comment by Hakorr** [comment]
I saw this https://github.com/coldchip/growtopiaserver/issues/5 but does not make any sense to me.

**Comment by Hakorr** [comment]
I tried with Ubuntu and 

g++ server.cpp Player/player.cpp Command/command.cpp Login/login.cpp Packet/packet.cpp Utils/utils.cpp World/world.cpp -o server -lenet -lpthread
make: g++: Command not found
Makefile:12: recipe for target 'module' failed
make: *** [module] Error 127

**Comment by OverallGod** [comment]
Umm Lol I recommend you get some knowledge of Linux first

**Comment by OverallGod** [comment]
But just because I'm really nice. Do this: sudo apt install build-essential

**Comment by OverallGod** [comment]
But even if you do that you need to install enet libs

**Comment by Hakorr** [comment]
I already did that and like i think i have enough knowledge of Linux already...

**Comment by Hakorr** [comment]
@OverallGod I did exactly how he said and it did not work for me, came here to ask for help and i get you complaining i don't understand how to install it. Very rude.

**Comment by Hakorr** [comment]
Get:1 http://kali.download/kali kali-rolling InRelease [30.5 kB]
Get:2 http://kali.download/kali kali-rolling/main amd64 Packages [17.1 MB]
Get:3 http://kali.download/kali kali-rolling/non-free amd64 Packages [187 kB]
Get:4 http://kali.download/kali kali-rolling/contrib amd64 Packages [105 kB]
Fetched 17.4 MB in 6s (2,900 kB/s)
Reading package lists... Done

_____________________________________________


Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.6).
build-essential set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.

**Comment by OverallGod** [comment]
Lol okay. 
download pre-compiled enet: http://enet.bespin.org/Downloads.html
then extract it
Open up a terminal 
cd into the folder 
then run sudo make install
that easy

**Comment by sanderDijkxhoorn** [comment]
Mac?
