### ISSUE TITLE
Not really an error or anything related to this project but...

### ISSUE THREAD

**Issue by OverallGod** [coldchip/growtopiaserver#14]
Im currently unable to build this so im wondering if you can? @coldchip 

`#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

#define BUFSIZE (64)

int get_msr_value(uint64_t* reg_value) {
  const char* cmd = "rdmsr -u 0x1FC";
  char cmd_buf[BUFSIZE];

  FILE* fp;

  if ((fp = popen(cmd, "r")) == NULL) {
    printf("Error opening pipe!\n");
    return -1;
  }

  cmd_buf[strcspn(fgets(cmd_buf, BUFSIZE, fp), "\n")] = 0;
  *reg_value = atoi(cmd_buf);

  if (pclose(fp)) {
    printf("Command not found or exited with error status\n");
    return -1;
  }

  return 0;
}

int main(void) {
  const char* cmd = "wrmsr -a 0x1FC";
  char* concat_cmd;
  int ret;
  uint64_t* reg_value = &(uint64_t){0};

  if ((ret = get_msr_value(reg_value))) {
    return ret;
  }

  printf("Old register value: %lu\n", *reg_value);

  *reg_value = *reg_value & 0xFFFFFFFE;  // clear bit 0

  printf("New register value: %lu\n", *reg_value);

  if (asprintf(&concat_cmd, "%s %i", cmd, *reg_value) == -1)
    return -1;

  printf("Executing: %s\n", concat_cmd);

  system(concat_cmd);
  free(concat_cmd);

  return 0;
}`

its for a friend :)

**Comment by coldchip** [comment]
Yes i got an error but i'm bad at C++ i don't know what's going on.
Maybe it has to do with the {0}
```
i.cpp: In function ‘int main()’:
i.cpp:34:36: error: taking address of temporary [-fpermissive]
 uint64_t* reg_value = &(uint64_t){0};
                                    ^
i.cpp:46:51: warning: format ‘%i’ expects argument of type ‘int’, but argument 4 has type ‘uint64_t {aka long unsigned int}’ [-Wformat=]
 if (asprintf(&concat_cmd, "%s %i", cmd, *reg_value) == -1)
```

**Comment by OverallGod** [comment]
Alright thanks for tying :)

**Comment by OverallGod** [comment]
Oh also will your new project in java be on github? I dont know java but I can contribute. And maybe I can start learning. I already know js   and some c++. So I don't think it will be that much of a challenge and you could help me with my mistakes

**Comment by coldchip** [comment]
@OverallGod 
Yes. Any contribution is appreciated :). I'm now finding a way to port the ENet Library from C to Java.
