### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by OverallGod** [coldchip/growtopiaserver#15]
Sorry once more for filling up your issues but how can I contact you Other than using issues.
What timezone are you in? I dont want to message you at 3 am when your sleeping.

US Central time and its currently 12:03AM
Im normally up for 18 out of the 24 hours in a day.

**Comment by coldchip** [comment]
@OverallGod 
My Discord is coldchip#6359
My timezone is UTC+8(Singapore)
It's okay i don't sleep at 3AM xD

**Comment by OverallGod** [comment]
Awesome thanks :)

**Comment by coldchip** [comment]
np :)
