### ISSUE TITLE
help me install server

### ISSUE THREAD

**Issue by NoNamexe** [coldchip/growtopiaserver#19]
root@ubuntu-18:~/growtopiaserver# make
# swig -java -outdir src/ru/ColdChip/GrowtopiaServer/ENetJava -package ru.Co                                                                                            ldChip.GrowtopiaServer.ENetJava ENetJNIToolChain/enet.i
# ^^ PLEASE DO NOT UNCOMMENT THE TOP LINE ^^
gcc -c ENetJNIToolChain/enet/unix.c -fPIC -DHAS_SOCKLEN_T=1 -o ENetJNIToolCh                                                                                            ain/enet/unix.lo
gcc -c ENetJNIToolChain/enet/win32.c -fPIC -o ENetJNIToolChain/enet/win32.lo
gcc -c ENetJNIToolChain/enet/protocol.c -fPIC -o ENetJNIToolChain/enet/proto                                                                                            col.lo
gcc -c ENetJNIToolChain/enet/peer.c -fPIC -o ENetJNIToolChain/enet/peer.lo
gcc -c ENetJNIToolChain/enet/packet.c -fPIC -o ENetJNIToolChain/enet/packet.                                                                                            lo
gcc -c ENetJNIToolChain/enet/list.c -fPIC -o ENetJNIToolChain/enet/list.lo
gcc -c ENetJNIToolChain/enet/host.c -fPIC -o ENetJNIToolChain/enet/host.lo
gcc -c ENetJNIToolChain/enet/compress.c -fPIC -o ENetJNIToolChain/enet/compr                                                                                            ess.lo
gcc -c ENetJNIToolChain/enet/callbacks.c -fPIC -o ENetJNIToolChain/enet/call                                                                                            backs.lo
gcc -c ENetJNIToolChain/enet_wrap.c -o ENetJNIToolChain/enet_wrap.o
gcc -shared ENetJNIToolChain/enet/*.lo ENetJNIToolChain/enet_wrap.o -o Lib/l                                                                                            ibenet.so
rm -r ENetJNIToolChain/enet/*.lo
javac -sourcepath src src/ru/ColdChip/GrowtopiaServer/Server.java
make: javac: Command not found
Makefile:10: recipe for target 'module' failed
make: *** [module] Error 127
root@ubuntu-18:~/growtopiaserver#

**Comment by coldchip** [comment]
install the java compiler and the java vm using: 

`sudo apt-get install openjdk-8-jdk`

https://www.linode.com/docs/development/java/install-java-on-ubuntu-16-04/
