### ISSUE TITLE
More problems

### ISSUE THREAD

**Issue by OverallGod** [coldchip/growtopiaserver#2]
: fatal error: algorithm: No such file or directory
 #include <algorithm>
          ^~~~~~~~~~~

**Comment by coldchip** [comment]
This types of error means that your compiler (g++) is broken or you aren't using a Linux operating system.

**Comment by OverallGod** [comment]
I'm using peppermint. How do I reinstall g++ or should I just install Ubuntu or something like that

**Comment by OverallGod** [comment]
also how do i install enet? I downloaded it and ran the commands it told me to but i just get errors
