### ISSUE TITLE
I can't connect server

### ISSUE THREAD

**Issue by NoNamexe** [coldchip/growtopiaserver#20]
Why

**Comment by NoNamexe** [comment]
.

**Comment by NoNamexe** [comment]
Server ia online

**Comment by NoNamexe** [comment]
I connect use virtual hosts

**Comment by NoNamexe** [comment]
And open growtopia

**Comment by NoNamexe** [comment]
growtopia stuck on getting server address

**Comment by NoNamexe** [comment]
My server control panel link :https://laboro.serveo.net
I forward

**Comment by coldchip** [comment]
Your system must have a web server on port 80 which contains the file growtopia/server_data.php so growtopia knows where to lookup the server. 

example: https://www.growtopiagame.com/growtopia/server_data.php

**Comment by NoNamexe** [comment]
Ok thanks
