### ISSUE TITLE
So, I start the server then I add to the hosts file 127.0.0.1 growtopia1.com do I need to run run.py too? Because run.py doesn’t really work that great and not at all for Mac..

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [coldchip/growtopiaserver#21]

**Comment by sanderDijkxhoorn** [comment]
Where can I change the ip because you changed to code that doesn’t look like the original code from GrowtopiaNoobs

**Comment by coldchip** [comment]
You can change it in 
src/ru/ColdChip/GrowtopiaServer/Server.java 
at line 123

**Comment by OverallGod** [comment]
@sanderDijkxhoorn he didn't change growtopianoobs code this is a different server In a different language.
Growtopianoobs  server is in c++ this one is in java.
