### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by Bexpg-0** [coldchip/growtopiaserver#34]
?

**Comment by Bexpg-0** [comment]
How to download java to linux etc. Can you tell all commands

**Comment by Bexpg-0** [comment]
How to build & run

**Comment by coldchip** [comment]
I guess Google had the answers and the instructions in clearly written in README.md! Please stop spamming my other repository with off-topic contents.

**Comment by Bexpg-0** [comment]
Read.me not full

**Comment by Bexpg-0** [comment]
And i get error
