### ISSUE TITLE
I installed enet but still this...

### ISSUE THREAD

**Issue by OverallGod** [coldchip/growtopiaserver#5]
g++ server.cpp Player/player.cpp Command/command.cpp Login/login.cpp Packet/packet.cpp Utils/utils.cpp World/world.cpp -o server -lenet -lpthread
/usr/bin/ld: cannot find -lenet
collect2: error: ld returned 1 exit status
Makefile:12: recipe for target 'module' failed
make: *** [module] Error 1

**Comment by coldchip** [comment]
Seems like the compiler can't find where enet is?!?!
Try to compile enet with `make` and after that `make install`
https://github.com/lsalzman/enet

**Comment by OverallGod** [comment]
Well that fixed it thanks
