### ISSUE TITLE
First it worked but I didn't use it for a while how do I start a http server on mac xD

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [coldchip/growtopiaserver#9]
First it worked but I didn't use it for a while how do I start a http server on mac xD

**Comment by OverallGod** [comment]
You can use python or nodejs

**Comment by sanderDijkxhoorn** [comment]
> You can use python or nodejs

Uhhm but how?
Start.py Doesn't work for me and the server app doesn't work either...

**Comment by sanderDijkxhoorn** [comment]
Everytime im stuck at located server etc. then it says time out maybe server is rebbootiing message
